exclude_patterns:
- "**/__tests__/**"
checks:
  complex-logic:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
